### ISSUE TITLE
gettext build fails while attempting to link autosprintf.obj since the file is not created

### ISSUE THREAD

**Issue by ryanjsims** [wingtk/gvsbuild#940] opened 2023-05-12 05:49 UTC
When attempting to build gtk3/gtk4 using the directions given in the readme, gettext fails to build with the message:

```
LINK : fatal error LNK1181: cannot open input file 'vs17\release\x64\asprintf\autosprintf.obj'
```

It appears that the build for this project is broken and isn't generating all the files needed?
[gvsbuild-log.txt](https://github.com/wingtk/gvsbuild/files/11459451/gvsbuild-log.txt)

**Comment by danyeaw** [comment] 2023-05-13 10:57
Hi @ryanjsims, thanks for the bug report. Can you please provide more information so that someone could try to reproduce the issue you are having? What version of Windows? What command did you run? What gvsbuild version and how did you install it? What version of Visual Studio? Thanks!

**Comment by danyeaw** [comment] 2023-07-01 16:27
Since I don't know how to reproduce this, I'm going to go ahead and close it until more information can be posted. Thanks!

**Closed by danyeaw** 2023-07-01 16:27 UTC
