### ISSUE TITLE
Does this pkg-config mix with vcpkg?

### ISSUE THREAD

**Issue by acidtonic** [wingtk/gvsbuild#443] opened 2021-10-12 18:19 UTC
I am struggling to build gtkmm since this project doesn't and I cannot seem to get the pkg-config that this project builds to honor or find the .pc files installed from vcpkg....

Is this supposed to work? I have like 3 stacks installed here trying to get something to build for windows.... After gvsbuild finished I expected to set pkg-config-executable to the one gvsbuild built and set PKG_CONFIG_PATH to point to the folder of .pc files dropped from vcpkg but it just doesn't seem to find anything that way.

At the end of the day I would just use msys2 but thanks to nvidia cuda not supporting anything other than visual studio I am stuck going down this painful road. Ideally I'd build gtkmm from source after gvsbuild finishes but that required m4/perl and the perl scripts ran from windows cmd shell required missing rm commands but the bash shell can't run exe files so I had to set path to find both and the build still failed after getting gmmproc commands to finally run.

Can gvsbuild be easily tweaked to build gtkmm? It's literally the last thing I need besides gdl/gdlmm yet it seems impossible to get built.

**Comment by danyeaw** [comment] 2021-11-26 19:17
Dupe of #393

**Closed by danyeaw** 2021-11-26 19:17 UTC
