### ISSUE TITLE
libffi build failure

### ISSUE THREAD

**Issue by TingPing** [wingtk/gvsbuild#251] opened 2018-03-15 06:03 UTC
```
[9/10] Linking target src/ffi-7.dll.
FAILED: src/ffi-7.dll
link @src/ffi-7.dll.rsp
   Creating library src\\ffi.lib and object src\\ffi.exp
x86_ffiold-msvc.c.obj : error LNK2019: unresolved external symbol _ALIGN referenced in function _ffi_prep_args
src/ffi-7.dll : fatal error LNK1120: 1 unresolved externals
```

This happens on both 2015 and 2017. I don't know how a module can have so many problems especially when it worked a week ago...

Just need to find which lib provides that symbol.

CC @nirbheek since he wrote the meson files.

**Comment by nirbheek** [comment] 2018-03-15 07:24
CCing @MathieuDuponchelle since he's been looking at libffi

**Comment by nirbheek** [comment] 2018-03-15 08:12
libffi branch `meson` is broken because @MathieuDuponchelle rebased it on top of libffi master. Till he fixes it, you can use the `meson-1.14` branch that I just pushed.

**Comment by TingPing** [comment] 2018-03-15 08:23
Alright. Sidenote @nacho we need to just outright ban building from the tip of a branch, it should always set a specific commit.

**Comment by nirbheek** [comment] 2018-03-15 09:16
The `meson-x.yy` branches are 'stable' and won't be rebased, so you can use those safely.

**Comment by MathieuDuponchelle** [comment] 2018-03-15 18:12
I was able to reproduce, had only tested against msvc in 64-bit mode, the issue was that we maintain `ffiold_msvc.c` on top of master and "ALIGN" was renamed to "FFI_ALIGN", I have no idea why the compiler was complaining about "_ALIGN" though!

**Comment by TingPing** [comment] 2018-03-15 19:53
The linker always seems to add `_` for local symbols or something. I'm no msvc export though.

**Comment by MathieuDuponchelle** [comment] 2018-03-15 20:11
@TingPing , can you confirm if this fixes the issue for you so we can close this?

**Comment by TingPing** [comment] 2018-03-15 22:24
It did fix it, thanks.

**Closed** 2018-03-15 22:24 UTC

**Comment by MathieuDuponchelle** [comment] 2018-03-16 00:04
cool, sorry about that!
