### ISSUE TITLE
--same-python option doesn't support spaces in Python path

### ISSUE THREAD

**Issue by doadin** [wingtk/gvsbuild#472] opened 2021-12-31 08:06 UTC
'Debug: running: C:\Program Files\Python37\python.exe steup.py install, cwd=C:\gtk-build\build\x64\release\pycairo, path+=None
'C:\Program' is not recognized as an internal or external command, operable program or batch file.'

This issue is seen when using --same-python

I'm guessing there is a escaping issue somewhere, this could maybe be fixed by arg python_dir.

https://github.com/wingtk/gvsbuild/blob/cefd8cbb0c25a7bfc245cfea4e0bf480695b4d4b/gvsbuild/utils/builder.py#L1122

**Comment by danyeaw** [comment] 2022-01-04 02:22
@doadin So this is an issue with using `--same-python` and having a space in the path to the Python location, right?

**Comment by doadin** [comment] 2022-01-04 04:14
Yes.

**Comment by danyeaw** [comment] 2022-04-26 00:27
@doadin I am not able to reproduce this. I installed Python 3.10.4 embedded to C:\Python Test\ and then ran:

```
PS C:\gtk-build\github\gvsbuild> & 'C:\Python Test\python.exe' build.py build --same-python --from-scratch gtk3
```

Everything seems to work fine.

What were you trying to do when you ran: 'Debug: running: C:\Program Files\Python37\python.exe steup.py install, cwd=C:\gtk-build\build\x64\release\pycairo, path+=None

**Comment by doadin** [comment] 2022-04-26 01:05
I was just running a normal build similar to "python build.py build --same-python --from-scratch gtk3" its been so long I don't remember the exact but if you want to replicate more closely I ran the build with python installed in Program Files and added to PATH OS environment variable.

**Comment by danyeaw** [comment] 2022-05-02 01:43
I think this is fixed now, please reopen an issue if you run in to another problem with using `--same-python`, thanks!

**Closed by danyeaw** 2022-05-02 01:43 UTC
Labels: bug
