### ISSUE TITLE
FAILED: gdk-pixbuf/loaders.cache (2.42.12) Win 10, gvsbuild build gtk4

### ISSUE THREAD

**Issue by daliyou** [wingtk/gvsbuild#1397] opened 2024-07-30 13:11 UTC
I am trying to gvsbuild build gtk4. It gives following failor, Could you please indicate me the reasons and solutions? Thanks

```
-- Installing: C:/gtk-build/build/x64/release/libpng-rel/lib/libpng/libpng16-relwithdebinfo.cmake

(tar) Exporting gdk-pixbuf
Building project gdk-pixbuf (2.42.12)
[1/3] Generating gdk-pixbuf/loaders.cache with a custom command (wrapped by meson to set PATH, to capture output)
**FAILED: gdk-pixbuf/loaders.cache**
"C:\Users\youdali\AppData\Local\Programs\Python\Python312\python.exe" "C:\gtk-build\tools\meson-1.4.1\meson.py" "--internal" "exe" "--unpickle" "C:\gtk-build\build\x64\release\gdk-pixbuf\_gvsbuild-meson\meson-private\meson_exe_gdk-pixbuf-query-loaders_16cdceb611d2fa0909d0e380855d877266fee48a.dat"
while executing ['C:\\gtk-build\\build\\x64\\release\\gdk-pixbuf\\_gvsbuild-meson\\gdk-pixbuf\\gdk-pixbuf-query-loaders.exe']
--- stderr ---

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\youdali\AppData\Local\Programs\Python\Python312\Lib\site-packages\gvsbuild\utils\builder.py", line 540, in build
    if self.__build_one(p):
![gdk-pixbuf](https://github.com/user-attachments/assets/4e5ab6c6-d5c3-4cd5-8fda-d1db05c95ae4)

```

**Comment by danyeaw** [comment] 2024-07-30 23:51
Duplicate of #1378.

**Closed by danyeaw** 2024-07-30 23:51 UTC
