### ISSUE TITLE
Determine which version of VS2017 is installed with --vs-ver

### ISSUE THREAD

**Issue by pbsinnett** [wingtk/gvsbuild#297] opened 2018-12-29 01:33 UTC
Hi,

First of all, thanks for providing this very useful package! I have one suggestion that might improve ease of use.

When using the --vs-ver 15 argument, the path defaults to the professional version of VS2017. The paths for each version of VS2017 is different. Perhaps we could make it a little easier than having to specify the install path in VS2017's case by specifying 15c, 15e or 15p for community, enterprise and professional respectively.

**Comment by TingPing** [comment] 2018-12-29 02:10
Duplicate of #252

**Closed by TingPing** 2018-12-29 02:10 UTC
