### ISSUE TITLE
Unable to Build GTK Library in window 10

### ISSUE THREAD

**Issue by lifetedy** [wingtk/gvsbuild#622] opened 2022-07-19 14:01 UTC
Please help me I was stacked on installing GTK3  in window 10 .Running command "gvsbuild build gtk3" in power shell generate the following problem

(.venv) PS C:\gtk-build\github\gvsbuild> gvsbuild build gtk3
Cleaning up the build environment
Checking msys tool
Using C:\tools\msys64 for msys installation
Checking Msvc tool

Visual Studio installation(s) found:
    Visual Studio Build Tools 2022 @ C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    Visual Studio Build Tools 2019 @ C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
Downloading packages
Building project nuget (6.2.1)
Feeds used:

Argument cannot be null or empty
Parameter name: primarySources
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 537, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\builder.py", line 630, in __build_one
    proj.prepare_build_dir()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\utils\base_project.py", line 390, in prepare_build_dir
    self.unpack()
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\tools.py", line 325, in unpack
    self.mark_deps = self.setup(True)
  File "C:\gtk-build\github\gvsbuild\.venv\lib\site-packages\gvsbuild\tools.py", line 298, in setup
    subprocess.check_call(cmd, shell=True)
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\gtk-build\tools\nuget-6.2.1\nuget.exe install python -Version 3.10.5 -OutputDirectory C:\gtk-build\tools' returned non-zero exit status 1.
Error: python build failed

**Comment by danyeaw** [comment] 2022-07-20 02:32
@lifetedy Thanks for submitting this issue. Unfortunately, I tried using the `--from-scratch` option which removes all the installed tools, and I can't reproduce this.

One thing I notice is that it looks like your feeds used is empty, and I am getting:
```
Feeds used:
  C:\Users\dan\.nuget\packages\
  https://api.nuget.org/v3/index.json
```

I don't think this is related to the issue, but did you mean to put your virtualenv in C:\gtk-build\github\gvsbuild.venv instead of C:\gtk-build\github\gvsbuild\.venv?

**Comment by lifetedy** [comment] 2022-07-20 05:42
I follow the instruction given to install GTK using gvsbuild
I used package manager Chocolatey and  these are the instruction given 
1. Install Git---done
2. install msys2---done
3. Install the gvsbuild dependencies :Visualstudio2022-workload-vctools and Python--done
4. Install gvsbuild: mkdir C:\gtk-build\github
cd C:\gtk-build\github
git clone https://github.com/wingtk/gvsbuild.git
5.At last: cd C:\gtk-build\github\gvsbuild
python -m venv .venv
.\.venv\Scripts\activate.ps1
pip install .
gvsbuild build gtk3

The problem occurs while I running the command "gvsbuild build gtk3" in PowerShell. I follow the exact instruction . what do you mean  from --from-scratch option?  Can you explain for me?

**Comment by danyeaw** [comment] 2022-07-20 19:44
HI @lifetedy, I just meant that I used the `--from-scratch` option to reset gvsbuild locally to a "fresh install" and I can't reproduce the issue.

Since it looks like it is an issue with nuget, what do you get if you run nuget standalone?

```Powershell
PS > cd C:\gtk-build\tools\nuget-6.2.1\
PS C:\gtk-build\tools\nuget-6.2.1> .\nuget.exe install python -Version 3.10.5 -OutputDirectory C:\Users\dan\Downloads
```

Change `C:\Users\dan\Downloads` to a suitable local directory on your computer. Is it successful at installing Python?

Another thing you could try is `gvsbuild build --same-python gtk3`. This will use the Python that you used to run gvsbuild instead of a new copy downloaded by nuget.

**Comment by lifetedy** [comment] 2022-07-21 11:19
Thank you danyeaw the issue was as you described nuget  problem and the feeds are empty . I run the command you provided  and the same message appear that is the feeds are empty.  I create the local feed using the command  nuget.exe source add -name .nuget -Source https://api.nuget.org/v3/index.json. The problem is solved . I install the GTK3.  I Install MSYS2,Python 3.10, visualstudio2022-workload-vctools,gvsbuild  Build  GTK. But unable to import gtk in my python file both in Anaconada pyhton and Python 3.10 IDE.   when I run the file it display "ModuleNotFoundError: No module named 'gtk'"

**Comment by danyeaw** [comment] 2022-07-21 13:29
Good news you resolved the issue with nuget. I am wondering now why you didn't have any feeds and if we need to check for that with gvsbuild. @nacho, do you have any thoughts?

@lifetedy did you add GTK to your PATH with `$env:Path = "C:\gtk-build\gtk\x64\release\bin;" + $env:Path`?

**Comment by lifetedy** [comment] 2022-07-21 14:21
Yes  I add the GTK to the path. How  I can  check feed used using gvsbuild.? Not that  for testing purpose i use eSpeakGUI.py

**Comment by danyeaw** [comment] 2022-07-21 15:39
If you want to run PyGObject with GTK, you'll need to do more than just compile GTK3:

```
PS > gvsbuild build --enable-gi --py-wheel gobject-introspection gtk3 pycairo pygobject adwaita-icon-theme hicolor-icon-theme
```

Then you need to activate the virtualenv you are using for eSpeakGUI and install the wheels you built:

```
(venv) PS > Get-ChildItem C:\gtk-build\build\x64\release\*\dist\*.whl | ForEach-Object -process { python -m pip install $_ }
```

**Comment by danyeaw** [comment] 2022-07-22 00:55
Closing this since I don't think there is an issue with gvsbuild here.

**Closed by danyeaw** 2022-07-22 00:55 UTC
