### ISSUE TITLE
gvsbuild build gtk4 fails with python 3.12.0 with ModuleNotFound: No module named 'distutils'

### ISSUE THREAD

**Issue by jeffreyeast** [wingtk/gvsbuild#1138] opened 2023-11-14 23:27 UTC
Another issue mentioned the python 3.12.0 distutils issue, but that was closed. Following the instructions in readme.md, the step

gvsbuild build gtk4

fails. I tried installing setuptools, but that didn't solve the issue.  Any suggestions?  Thanks.

The tail showing the error:

(tar) Exporting pcre2
Building project pcre2 (10.42)
[0/1] Installing files.Installing pcre2-8.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-8.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-8.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-posix.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-posix.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-posix.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-16.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-16.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-16.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-32.dll to C:\gtk-build\gtk\x64\release\bin
Installing pcre2-32.lib to C:\gtk-build\gtk\x64\release\lib
Installing pcre2-32.pdb to C:\gtk-build\gtk\x64\release\bin
Installing pcre2grep.exe to C:\gtk-build\gtk\x64\release\bin
Installing pcre2grep.pdb to C:\gtk-build\gtk\x64\release\bin
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\pcre2.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\pcre2\src/pcre2posix.h to C:\gtk-build\gtk\x64\release\include
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\meson-private\libpcre2-8.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\meson-private\libpcre2-16.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig
Installing C:\gtk-build\build\x64\release\pcre2\_gvsbuild-meson\meson-private\libpcre2-32.pc to C:\gtk-build\gtk\x64\release\lib\pkgconfig

(tar) Exporting glib
Building project glib (2.78.1)
[55/716] Generating gio/gdbus-daemon-generated with a custom command
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c
"C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Scripts\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../gio/dbus-daemon.xml"
Traceback (most recent call last):
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>
    from . import utils
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[56/716] Linking target gmodule/gmodule-2.0-0.dll
   Creating library gmodule\gmodule-2.0.lib and object gmodule\gmodule-2.0.exp
[64/716] Compiling C object gio/gio.exe.p/gio-tool.c.obj
C:\gtk-build\build\x64\release\glib\gio\gio-tool.c(281) : warning C4702: unreachable code
[69/716] Compiling C object gio/gio.exe.p/gio-tool-mount.c.obj
../gio/gio-tool-mount.c(134): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
[71/716] Compiling C object gio/win32/libgiowin32.a.p/gwinhttpfileoutputstream.c.obj
../gio/win32/gwinhttpfileoutputstream.c(143): warning C4245: 'function': conversion from 'int' to 'DWORD', signed/unsigned mismatch
[72/716] Compiling C object gio/win32/libgiowin32.a.p/gwinhttpfile.c.obj
../gio/win32/gwinhttpfile.c(323): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\glib.py", line 47, in build
    Meson.build(self)
  File "C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja
    self.__execute(
  File "C:\Users\JeffE\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
PS C:\WINDOWS\system32>

**Comment by danyeaw** [comment] 2023-11-15 02:09
Hi @jeffreyeast! Thanks for reporting the issue. It looks like this is an upstream bug with GLib here: https://gitlab.gnome.org/GNOME/glib/-/issues/3134

**Comment by ChandlerVS** [comment] 2023-12-17 15:11
> Hi @jeffreyeast! Thanks for reporting the issue. It looks like this is an upstream bug with GLib here: https://gitlab.gnome.org/GNOME/glib/-/issues/3134

Looks like a resolution to this was merged (https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3740)

Is there a way we can take advantage of this through a CLI flag or something?

**Comment by PlatinumLucario** [comment] 2024-01-19 17:05
I should also note that this *exact* same issue also occurs when running ``gvsbuild build gtk3`` as well.

This issue is due to an issue in glib.py:
https://github.com/wingtk/gvsbuild/blob/main/gvsbuild/projects/glib.py#L27

This is pretty much why it won't build with Python 3.12 and currently requires using Python version < 3.12, because gvsbuild is downloading an outdated version of GLib.

The latest release of GLib is found here: https://gitlab.gnome.org/GNOME/glib/-/releases/2.79.0

I would suggest updating the version number and the hash code to the one used in GLib 2.79.0.

And if anyone is updating it, check all the other packages, just to make sure they're all downloading the latest version too.

**Comment by PlatinumLucario** [comment] 2024-01-19 17:51
@danyeaw Would it be possible for you to update the dependency GLib and others that may be out of date?

**Comment by danyeaw** [comment] 2024-01-19 18:03
Hi @PlatinumLucario, the latest stable released version of GLib is 2.78.3 which is the version we have in Gvsbuild.

**Comment by PlatinumLucario** [comment] 2024-01-20 06:25
Hi @danyeaw, I can confirm that changing the version and sha256 hash strings in glib.py from this:
```python
@project_add
class GLib(Tarball, Meson):
    def __init__(self):
        Project.__init__(
            self,
            "glib",
            version="2.78.3",
            lastversion_even=True,
            repository="https://gitlab.gnome.org/GNOME/glib",
            archive_url="https://download.gnome.org/sources/glib/{major}.{minor}/glib-{version}.tar.xz",
            hash="609801dd373796e515972bf95fc0b2daa44545481ee2f465c4f204d224b2bc21",
            dependencies=[
                "ninja",
                "meson",
                "pkgconf",
                "gettext",
                "libffi",
                "zlib",
                "pcre2",
            ],
            patches=[
                "glib-package-installation-directory.patch",
            ],
        )

    def build(self):
        Meson.build(self)
        self.install(r".\LICENSES\* share\doc\glib")
```
To this:
```python
@project_add
class GLib(Tarball, Meson):
    def __init__(self):
        Project.__init__(
            self,
            "glib",
            version="2.79.0",
            lastversion_even=True,
            repository="https://gitlab.gnome.org/GNOME/glib",
            archive_url="https://download.gnome.org/sources/glib/{major}.{minor}/glib-{version}.tar.xz",
            hash="d7ebde5505f5c4741a04ffe32f6927bd165b13caaabe18e962ddc58c811f84c9",
            dependencies=[
                "ninja",
                "meson",
                "pkgconf",
                "gettext",
                "libffi",
                "zlib",
                "pcre2",
            ],
            patches=[
                "glib-package-installation-directory.patch",
            ],
        )

    def build(self):
        Meson.build(self)
        self.install(r".\LICENSES\* share\doc\glib")
```
Actually worked in Python 3.12! As seen below:
![image](https://github.com/wingtk/gvsbuild/assets/1906189/698d1e77-bd4c-4e68-b680-d9d8d7c2ea53)
![image](https://github.com/wingtk/gvsbuild/assets/1906189/e1393721-8d47-4308-8074-92e4fc6c0204)

Is 2.79.0 a stable release? Looks like it is, unless I missed something in the releases page that says "pre-release" or something, which I can't see.

**Comment by PlatinumLucario** [comment] 2024-01-20 06:37
Also, I can confirm that this also works for ``gvsbuild build gtk4`` too
![image](https://github.com/wingtk/gvsbuild/assets/1906189/5a5b2c09-d2c4-409c-8d64-fa7f93fa0d54)

**Comment by pbor** [comment] 2024-01-20 10:08
In glib convention, odd numbers like 79 are development releases

**Comment by PlatinumLucario** [comment] 2024-01-20 11:50
Ah I see, that makes sense

**Comment by danyeaw** [comment] 2024-01-20 12:50
We can fix bugs before they are released in stable versions by adding a patch to the patches folder and putting the name of the patch in the GLib patches section. The patch that fixed this is here:

https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3740.patch

Is someone interested in submitting a PR? If not, I can create one later today. Maybe we should release version 2024.1.1 of Gvsbuild as well.

**Closed** 2024-01-20 22:57 UTC
Labels: bug

**Comment by FlooferLand** [comment] 2024-01-21 16:34
Still appears to be happening for me even with the patched `2024.1.1` gvsbuild version and Python 3.12.1

```
(tar) Exporting glib
Building project glib (2.78.3)
[2/655] Generating gio/gdbus-daemon-generated with a custom command
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c
"C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Scripts\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../gio/dbus-daemon.xml"
Traceback (most recent call last):
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>
    from . import utils
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[10/655] Compiling C object gio/gio.exe.p/gio-tool-set.c.obj
../gio/gio-tool-set.c(50): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
[12/655] Compiling C object gio/gresource.exe.p/gresource-tool.c.obj
../gio/gresource-tool.c(99): warning C4267: '=': conversion from 'size_t' to 'gint', possible loss of data
[15/655] Compiling C object gio/gio.exe.p/gio-tool-mount.c.obj
../gio/gio-tool-mount.c(134): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\glib.py", line 47, in build
    Meson.build(self)
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja
    self.__execute(
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\FlooferLand\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```

not sure if this is a glib-specific error since they seem to be having some trouble with `distutils` as well but it doesn't appear to be

**Comment by danyeaw** [comment] 2024-01-21 19:07
@FlooferLand Could you please retry with `gvsbuild build --from-scratch glib`? The error you are getting about `distutils.version` is what we patched out, so I expect you need to start over with everything clean.

**Comment by FlooferLand** [comment] 2024-01-22 05:25
Welp, now I get this:
```
Found ninja-1.11.1 at C:\gtk-build\tools\ninja-1.11.1\ninja.EXE
[16/1214] Generating gio/gdbus-daemon-generated with a custom command
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c
"C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Scripts\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org." "--output-directory" "gio" "--generate-c-code" "gdbus-daemon-generated" "--c-namespace" "_G" "../gio/dbus-daemon.xml"
Traceback (most recent call last):
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>
    from . import utils
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[17/1214] Generating gio/tests/gdbus-object-manager-example/objectmanager-gen with a custom command
FAILED: gio/tests/gdbus-object-manager-example/objectmanager-gen.h gio/tests/gdbus-object-manager-example/objectmanager-gen.c gio/tests/gdbus-object-manager-example/objectmanager-gen-org.gtk.GDBus.Example.ObjectManager.Animal.xml gio/tests/gdbus-object-manager-example/objectmanager-gen-org.gtk.GDBus.Example.ObjectManager.Cat.xml
"C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Scripts\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org.gtk.GDBus.Example.ObjectManager." "--c-namespace" "Example" "--c-generate-object-manager" "--output-directory" "gio/tests/gdbus-object-manager-example" "--generate-c-code" "objectmanager-gen" "--generate-docbook" "objectmanager-gen" "--symbol-decorator" "GDBUS_OBJECT_MANAGER_EXAMPLE_AVAILABLE_IN_ALL" "--symbol-decorator-header" "gdbus-example-objectmanager-visibility.h" "../gio/tests/gdbus-object-manager-example/gdbus-example-objectmanager.xml"
Traceback (most recent call last):
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>
    from . import utils
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[18/1214] Generating gio/tests/gdbus-object-manager-example/objectmanager-rst-gen with a custom command
FAILED: gio/tests/gdbus-object-manager-example/objectmanager-rst-gen-org.gtk.GDBus.Example.ObjectManager.Animal.rst gio/tests/gdbus-object-manager-example/objectmanager-rst-gen-org.gtk.GDBus.Example.ObjectManager.Cat.rst
"C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Scripts\python.exe" "gio/gdbus-2.0/codegen/gdbus-codegen" "--interface-prefix" "org.gtk.GDBus.Example.ObjectManager." "--generate-rst" "objectmanager-rst-gen" "--output-directory" "gio/tests/gdbus-object-manager-example" "../gio/tests/gdbus-object-manager-example/gdbus-example-objectmanager.xml"
Traceback (most recent call last):
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\dbustypes.py", line 22, in <module>
    from . import utils
  File "C:\gtk-build\build\x64\release\glib\_gvsbuild-meson\gio\gdbus-2.0\codegen\utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[22/1214] Compiling C object glib/gnulib/libgnulib.a.p/printf.c.obj
../glib/gnulib/printf.c(98): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
[28/1214] Compiling C object glib/gnulib/libgnulib.a.p/vasnprintf.c.obj
../glib/gnulib/vasnprintf.c(1113): warning C4267: '-=': conversion from 'size_t' to 'int', possible loss of data
[29/1214] Building translation po/ab/LC_MESSAGES/glib20-ab.mo
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 527, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 663, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\glib.py", line 47, in build
    Meson.build(self)
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 56, in build
    self.builder.exec_ninja(params="install", working_dir=ninja_build)
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 985, in exec_ninja
    self.__execute(
  File "C:\Users\FlooferLand\AppData\Local\pipx\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1041, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Users\FlooferLand\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: glib build failed
```
I've tried manually wiping out `C:\gtk-build\` as well before building

**Comment by FlooferLand** [comment] 2024-01-22 05:45
That worked, though I remember deleting `C:\gtk-build\` and it still didn't fix it earlier. I found out the hard way I still had the pip version of `gvsbuild` installed and it was using that.
I'd recommend adding a `--version` flag if possible! I remember trying to check what version I was using earlier on and it just giving me an error.

**Comment by danyeaw** [comment] 2024-01-22 22:35
Hi @FlooferLand, a version flag is a great idea. Are you interested in contributing that? It would probably would be a great first contribution if you are up for it.
