### ISSUE TITLE
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1. Error: gtk3 build failed

### ISSUE THREAD

**Issue by zhmmmm** [wingtk/gvsbuild#434] opened 2021-08-05 14:42 UTC
(tar) Exporting gtk3
Building project gtk3 (3.24.28)
[1/522] Generating gtkresources_c with a custom command
FAILED: gtk/gtkresources.c
"C:\gtk-build\gtk\x64\release\bin\glib-compile-resources.EXE" "gtk/gtk.gresources.xml" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/_gvsbuild-meson/gtk" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/gtk" "--sourcedir" "../gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.c" "--manual-register" "--dependency-file" "gtk/gtkresources.c.d"
[2/522] Generating gtkresources_h with a custom command
FAILED: gtk/gtkresources.h
"C:\gtk-build\gtk\x64\release\bin\glib-compile-resources.EXE" "gtk/gtk.gresources.xml" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/_gvsbuild-meson/gtk" "--sourcedir" "C:/gtk-build/build/x64/release/gtk3-24/gtk" "--sourcedir" "../gtk" "--c-name" "_gtk" "--internal" "--generate" "--target" "gtk/gtkresources.h" "--manual-register"
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 896, in build
    Meson.build(self, meson_params='-Dtests=false -Ddemos=false -Dexamples=false')
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 908, in exec_ninja
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 948, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
Error: gtk3 build failed

**Comment by danyeaw** [comment] 2021-11-07 14:03
Duplicate of #433.

**Closed by danyeaw** 2021-11-07 14:03 UTC
