### ISSUE TITLE
Fails to build GTK: RC terminating after preprocessor errors

### ISSUE THREAD

**Issue by sdroege** [wingtk/gvsbuild#441] opened 2021-09-28 10:26 UTC
See https://github.com/gtk-rs/gtk3-rs/pull/636/checks?check_run_id=3730997200

```
[...]
 [26/645] Compiling C object gdk/win32/libgdk-win32.a.p/gdktestutils-win32.c.obj
[27/645] Generating gtkmarshalers_c with a custom command
INFO: Reading ../gtk/gtkmarshalers.list...
[28/645] Compiling C object gdk/win32/libgdk-win32.a.p/gdkwin32langnotification.c.obj
[29/645] Generating gtkdbusgenerated.h with a custom command
[30/645] Generating gtkdbusgenerated.c with a custom command
[31/645] Generating gsettings-compile-gtk with a custom command
[32/645] Generating gtkmarshalers_h with a custom command
INFO: Reading ../gtk/gtkmarshalers.list...
[33/645] Generating gtkprivatetypebuiltins.h with a custom command (wrapped by meson to capture output)
[34/645] Generating gtkprivatetypebuiltins.c with a custom command (wrapped by meson to capture output)
[35/645] Generating gtk.rc with a custom command
[36/645] Compiling C object gdk/win32/libgdk-win32.a.p/gdkwin32id.c.obj
[37/645] Generating windows_compile_resources_gtk.rc with a custom command
FAILED: gtk/89afd8d@@gtk.rc@cus_gtk.res 
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\rc.EXE" "/nologo" "/fogtk/89afd8d@@gtk.rc@cus_gtk.res" "gtk/gtk.rc"
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um\winnt.h(253) : error RC2188: C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gtk\RCa05500(34) : fatal error RC1116: RC terminating after preprocessor errors

[38/645] Generating gtk/gtk-update-icon-cache.rc with a custom command
[39/645] Generating gtktypebuiltins.h with a custom command (wrapped by meson to capture output)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):

  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\builder.py", line 493, in build
(git) Cloning https://github.com/centricular/libffi.git to C:\gtk-build\src\git-exp\libffi
    if self.__build_one(p):
(git) Exporting directory C:\gtk-build\build\x64\release\libffi
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\builder.py", line 624, in __build_one
Building project libffi (git/meson-1.14)
    skip_deps = proj.build()
(tar) Exporting zlib
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\projects.py", line 903, in build
Building project zlib (1.2.11)
    Meson.build(self, meson_params='-Dtests=false -Ddemos=false -Dexamples=false')
(tar) Exporting glib
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\base_builders.py", line 76, in build
Building project glib (2.68.3)
    self.builder.exec_ninja(params='install', working_dir=ninja_build)
(tar) Exporting atk
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\builder.py", line 908, in exec_ninja
Building project atk (2.36.0)
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
Building project nasm (2.15.05)
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\builder.py", line 948, in __execute
(tar) Exporting libjpeg-turbo
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
Building project libjpeg-turbo (2.0.6)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 363, in check_call
(tar) Exporting libtiff-4
    raise CalledProcessError(retcode, cmd)
Building project libtiff-4 (4.2.0)
subprocess.CalledProcessError: Command 'ninja install' returned non-zero exit status 1.
(tar) Exporting jasper
Error: gtk3 build failed
Building project jasper (2.0.14)
(tar) Exporting libpng
Building project libpng (1.6.37)
(tar) Exporting gdk-pixbuf
Building project gdk-pixbuf (2.42.6)
(tar) Exporting freetype
Building project freetype (0d5f1dd37c056b4460a460d16fd1fbb06740e891)
(tar) Exporting libxml2
Building project libxml2 (2.9.12)
(tar) Exporting fontconfig
Building project fontconfig (2.13.0)
(tar) Exporting pixman
Building project pixman (0.40.0)
(tar) Exporting cairo
Building project cairo (1.16.0)
(tar) Exporting harfbuzz
Building project harfbuzz (2.8.0)
(git) Cloning https://github.com/fribidi/fribidi.git to C:\gtk-build\src\git-exp\fribidi
(git) Exporting directory C:\gtk-build\build\x64\release\fribidi
Building project fribidi (git/f2c9d50722cb60d0cdec3b1bafba9029770e86b4)
(tar) Exporting pango
Building project pango (1.48.4)
(tar) Exporting libepoxy
Building project libepoxy (1.5.5)
(tar) Exporting gtk3
Building project gtk3 (3.24.28)
Error: Process completed with exit code 1.
```

**Comment by danyeaw** [comment] 2021-10-02 19:14
@sdroege I am getting this same error with Gaphor when trying to rebuild gvsbuild to update PyGObject:
https://github.com/gaphor/gaphor/pull/1018

**Comment by danyeaw** [comment] 2021-10-06 01:43
@sdroege Have you been able to reproduce these errors locally? For me, the build is working fine locally, only failing on GitHub Actions.

**Comment by sdroege** [comment] 2021-10-06 04:57
I don't have any Windows setup available currently. But it fails 100% of the time on GitHub Actions.

**Comment by sdroege** [comment] 2021-10-11 09:29
Now fails to build because http://www.ece.uvic.ca/~frodo/jasper/software/jasper-2.0.14.tar.gz is broken :)

**Comment by nacho** [comment] 2021-10-11 09:37
Interesting... Is gdk-pixbuf building properly with openjpeg instead of jasper?

**Comment by nacho** [comment] 2021-10-11 09:45
FYI https://github.com/wingtk/gvsbuild/commit/3c7cf03482ca29d4dd2dd389bd5387a84435999f

**Comment by sdroege** [comment] 2021-10-11 09:58
```
Traceback (most recent call last):
Cleaning up the build environment
  File ".\build.py", line 48, in <module>
Checking msys tool
    args.func(args)
Checking Msvc tool
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\parser.py", line 165, in do_build
    builder.preprocess()
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\builder.py", line 431, in preprocess
    proj.dependencies = [Project.get_project(dep) for dep in proj.dependencies]
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\builder.py", line 431, in <listcomp>
    proj.dependencies = [Project.get_project(dep) for dep in proj.dependencies]
  File "D:\a\gtk3-rs\gtk3-rs\gvsbuild\gvsbuild\utils\base_project.py", line 369, in get_project
    return Project._dict[name]
KeyError: 'jasper'
```

**Comment by nacho** [comment] 2021-10-11 10:04
oops, please retry. I am blindly changing it since I do not have right now a windows machine

**Comment by nacho** [comment] 2021-10-11 11:20
I guess something specific with the windows sdk. Are you allowed to set the windows sdk you want to use?

**Comment by nacho** [comment] 2021-10-11 13:49
@sdroege sorry for the delay, it should be now pushed the missing file.

**Comment by sdroege** [comment] 2021-10-11 15:12
```
[...]
 [75/651] Generating gtkmarshalers_h with a custom command
INFO: Reading ../gtk/gtkmarshalers.list...
[76/651] Compiling C object gdk/gdk-3-vs16.dll.p/gdkseatdefault.c.obj
[77/651] Compiling C object gdk/gdk-3-vs16.dll.p/deprecated_gdkcolor.c.obj
[78/651] Generating gtkdbusgenerated.c with a custom command
[79/651] Generating gtkmarshalers_c with a custom command
INFO: Reading ../gtk/gtkmarshalers.list...
[80/651] Generating gtk.rc with a custom command
[81/651] Generating gtkprivatetypebuiltins.h with a custom command (wrapped by meson to capture output)
[82/651] Generating windows_compile_resources_gtk.rc with a custom command
FAILED: gtk/89afd8d@@gtk.rc@cus_gtk.res 
"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\rc.EXE" "/nologo" "/fogtk/89afd8d@@gtk.rc@cus_gtk.res" "gtk/gtk.rc"
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um\winnt.h(253) : error RC2188: C:\gtk-build\build\x64\release\gtk3-24\_gvsbuild-meson\gtk\RCa03268(34) : fatal error RC1116: RC terminating after preprocessor errors
```

Same problem as the original one still.

**Comment by danyeaw** [comment] 2021-10-13 01:19
I saw that Python had a similar issue with Win SDK 11 builds:
https://bugs.python.org/issue45220

They resolved it by updating the props file to avoid automatic selection of the latest SDK. Could we use a similar approach?

**Comment by fanc999** [comment] 2021-10-13 03:27
Hi,

Thanks @seungha-yang for the reproducing tip, I was able to eventually reproduce the issue by installing the Windows 11 SDK.  It seems to me the crux of the problem is that the Windows 11 SDK does not allow one to include `winuser.h` (but does allow `winver.h`--note that `gdk.rc` successfully builds) directly in the .rc files.  I was able to work around it by including `windows.h` instead.

So, I will open an MR in GTK so that we update the .rc files so that we do not try to include `winuser.h` there.

**Comment by nacho** [comment] 2021-10-14 15:36
yup, I was just waiting for it to be merged in case there is a last minute change

**Comment by nacho** [comment] 2021-10-14 16:26
the patch seems correct but maybe your git fetches the code using the unix line endings... I think we might need a new tarball...

**Comment by danyeaw** [comment] 2021-10-16 20:09
#446 fixes this for me. Nice job team for all the troubleshooting, patches, and other effort 👍

**Closed** 2021-10-17 09:24 UTC

**Comment by sdroege** [comment] 2021-10-17 10:24
Thanks, this solves it for me too
