### ISSUE TITLE
Failure building emeus: Native dependency 'gtk+-3.0' not found

### ISSUE THREAD

**Issue by syagev** [wingtk/gvsbuild#290] opened 2018-10-28 09:26 UTC
When building from `master` (commit 9f1b55d)  with the following command line:
```
python .\build.py build --enable-gi --gtk3-ver 3.20 -p x64 --msys-dir D:\Dev\msys64 --vs-ver 15 --win-sdk-ver 10.0.10586.0 --vs-install-path C:\Progra~2\Micros~4\2017\Enterprise --python-dir C:\Progra~1\Python36 gdk-pixbuf gtk3-full
```

Getting the following error:
```
Building project emeus (git/master)
Removing 00_win_no_script.patch
Removing 00_win_no_script.patch.patch-applied
Your branch is up to date with 'origin/master'.
Already up to date.
Current branch master is up to date.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file meson.build
The Meson build system
Version: 0.47.1
Source dir: C:\gtk-build\build\x64\release\emeus
Build dir: C:\gtk-build\build\x64\release\emeus-meson
Build type: native build
Project name: emeus
Project version: 0.99.1
Native C compiler: cl (msvc 19.15.26732.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports arguments -fstrict-aliasing: NO
Compiler for C supports arguments -Wpointer-arith: NO
Compiler for C supports arguments -Wmissing-declarations: NO
Compiler for C supports arguments -Wmissing-noreturn: NO
Compiler for C supports arguments -Wmissing-format-attribute: NO
Compiler for C supports arguments -Wmissing-prototypes: NO
Compiler for C supports arguments -Wformat=2: NO
Compiler for C supports arguments -Wstrict-prototypes: NO
Compiler for C supports arguments -Wnested-externs: NO
Compiler for C supports arguments -Wold-style-definition: NO
Compiler for C supports arguments -Wunused: NO
Compiler for C supports arguments -Wuninitialized: NO
Compiler for C supports arguments -Wshadow: NO
Compiler for C supports arguments -Wredundant-decls: NO
Compiler for C supports arguments -Wlogical-op: NO
Compiler for C supports arguments -Wcast-align: NO
Compiler for C supports arguments -Wno-unused-local-typedefs -Wunused-local-typedefs: NO
Compiler for C supports arguments -Werror=implicit: NO
Compiler for C supports arguments -Werror=init-self: NO
Compiler for C supports arguments -Werror=main: NO
Compiler for C supports arguments -Werror=missing-braces: NO
Compiler for C supports arguments -Werror=return-type: NO
Compiler for C supports arguments -Werror=array-bounds: NO
Compiler for C supports arguments -Werror=write-strings: NO
Has header "stdlib.h": YES
Has header "stdint.h": YES
Has header "stdbool.h": YES
Library m found: NO
Found pkg-config: C:\gtk-build\gtk\x64\release\bin\pkg-config.EXE (1.4.0)
Native dependency glib-2.0 found: YES 2.58.1

meson.build:158:0: ERROR:  Native dependency 'gtk+-3.0' not found

A full log can be found at C:\gtk-build\build\x64\release\emeus-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 363, in build
    if self.__build_one(p):
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 483, in __build_one
    skip_deps = proj.build()
  File "C:\gtk-build\github\gvsbuild\gvsbuild\projects.py", line 228, in build
    Meson.build(self, make_tests=True)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_builders.py", line 67, in build
    self.exec_vs(cmd)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\base_project.py", line 99, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 708, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\github\gvsbuild\gvsbuild\utils\builder.py", line 740, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Program Files\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Progra~1\Python36\python.exe C:\gtk-build\tools\meson-0.47.1\meson.py C:\gtk-build\build\x64\release\emeus C:\gtk-build\build\x64\release\emeus-meson --prefix C:\gtk-build\gtk\x64\release -Ddocs=false -Dintrospection=true --buildtype release' returned non-zero exit status 1.
Error: emeus build failed
```

Full log file can be found [here](https://gist.github.com/syagev/d499250e6a3e893a7a51049d439e1ec3)

**Comment by nacho** [comment] 2018-12-31 14:05
@guruDanny67 I think we should switch the default to gtk 3.24 and allow to select another version if needed

**Comment by guruDanny67** [comment] 2018-12-31 14:45
Agreed.

I try to upgrade to the 3.24.2 version but MSVC raises an error on
gtkresource.c because now the resource is a string and the MSVC has a limit
of 65535 char for any string :(

Il giorno lun 31 dic 2018 alle ore 15:05 Ignacio Casal Quinteiro <
notifications@github.com> ha scritto:

**Comment by pbor** [comment] 2019-01-02 08:32
@guruDanny67 with which version of glib?

As far as I can see that was fixed with https://gitlab.gnome.org/GNOME/glib/merge_requests/503 and was tracked in https://gitlab.gnome.org/GNOME/glib/issues/1580 

However it is not clear to me if it needs to be backported to the stable glib branch

**Comment by guruDanny67** [comment] 2019-01-02 14:56
The version of glib is 2.58.1, from the tarball in the ftp.

Also for gtk we use the tarball from the ftp site (the gtk 3.24.2 is made at 12 dec. 2018) but the merge on master is been done the day 10 dec. 2018 so it's not backported.

We use directly the tarball so the file gtkresource.c that gives the error is generated in the creation of the release and we simply use it.

I take a look at glib 2.58.2 and seems ok (the resource are written as guint8 data, not one big string) so the problem is not present in there and will not be also in the next 2.60.0 glib version.

At the end we only need a new gtk3 release made with the new, patched, glib-compile-resources.exe

**Closed** 2019-03-30 16:37 UTC
